In [36]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Reading a CSV File in Python
We create a sample CSV and read it using Python and pandas.

In [37]:
import pandas as pd

# --- Sample CSV Data --- Hardcoding/Stubbing/Manually creating the Data.
csv_data = """
id,name,age,city
1,Alice,25,New York
2,Bob,30,Los Angeles
3,Charlie,35,Chicago
4,David,40,Houston
5,Alice1,35,New York
"""

# Write CSV to a file
with open("sample_data.csv", "w") as f:
    f.write(csv_data)

# Read CSV -> loaded the data into a data frame
df = pd.read_csv("sample_data.csv")
# type(df)
df

120

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston
4   5   Alice1   35     New York

# 📘 Pandas DataFrame Basics
A DataFrame is a 2D table structure used for data analysis.

# 📘 15 Essential Pandas Operations
Each operation includes: one‑line summary + usage + example.

In [38]:
# 1️⃣ head() — View first rows
df.head(2)

# df.tail()

   id   name  age         city
0   1  Alice   25     New York
1   2    Bob   30  Los Angeles

In [39]:
# 2️⃣ info() — Summary of columns & types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   name    5 non-null      object
 2   age     5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [40]:
# 3️⃣ describe() — Statistical summary
df.describe()

             id        age
count  5.000000   5.000000
mean   3.000000  33.000000
std    1.581139   5.700877
min    1.000000  25.000000
25%    2.000000  30.000000
50%    3.000000  35.000000
75%    4.000000  35.000000
max    5.000000  40.000000

In [41]:
# 4️⃣ df['col'] — Select a column
# df
df['age']

0    25
1    30
2    35
3    40
4    35
Name: age, dtype: int64

In [42]:
# 5️⃣ df[['col1','col2']] — Select multiple columns
df[['name', 'city']]

      name         city
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4   Alice1     New York

In [43]:
# 6️⃣ Filtering rows — df[df['age'] > 30]
# df['age'] # ALL the values present in that column
# df['age'] > 30 # Returns if the condition is True/False. All rows returned.
df[df['age'] > 30] # Only rows meeting the criteria are fetched. FILTERED rows. *****

   id     name  age      city
2   3  Charlie   35   Chicago
3   4    David   40   Houston
4   5   Alice1   35  New York

In [44]:
# 7️⃣ sort_values() — Sort rows - REARRANGE the Rows. The is no loss of data.
# df
# df.sort_values(by='age', ascending=True)
df.sort_values(by='city', ascending=False)

   id     name  age         city
0   1    Alice   25     New York
4   5   Alice1   35     New York
1   2      Bob   30  Los Angeles
3   4    David   40      Houston
2   3  Charlie   35      Chicago

In [45]:
# 8️⃣ groupby() — Group and aggregate
df
df.groupby('city')['age'].mean()

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston
4   5   Alice1   35     New York

city
Chicago        35.0
Houston        40.0
Los Angeles    30.0
New York       30.0
Name: age, dtype: float64

In [46]:
# 9️⃣ assign() — Add new calculated column
# How to assign a default value to a NEW column:-
# df.assign(age_plus_10 = '')
# df.assign(age_plus_10 = 0)
# df.assign(age_plus_10 = True)

################################################
# TRANSFORMATION - calculated/processed/Modified
# How to ADD a NEW column
################################################
# How to assign based on an EXISTING column value -> assign to a NEW column:-
df1 = df.assign(age_plus_10 = df['age'] + 10)
df
df1

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston
4   5   Alice1   35     New York

   id     name  age         city  age_plus_10
0   1    Alice   25     New York           35
1   2      Bob   30  Los Angeles           40
2   3  Charlie   35      Chicago           45
3   4    David   40      Houston           50
4   5   Alice1   35     New York           45

In [47]:
# Example for rename from documentation - way to learn
df1 = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df1
df1.rename(columns={"A": "a", "B": "c"})
df1

   A  B
0  1  4
1  2  5
2  3  6

   a  c
0  1  4
1  2  5
2  3  6

   A  B
0  1  4
1  2  5
2  3  6

In [48]:
# 🔟 rename() — Rename columns
df.rename(columns={'name': 'full_name'})

   id full_name  age         city
0   1     Alice   25     New York
1   2       Bob   30  Los Angeles
2   3   Charlie   35      Chicago
3   4     David   40      Houston
4   5    Alice1   35     New York

In [49]:
# 1️⃣1️⃣ drop() — Remove columns
df.drop(columns=['city'])

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5   Alice1   35

In [57]:
# 1️⃣2️⃣ fillna() — Replace missing values
# df.fillna({'city': 'Unknown'})
df.fillna({'age': 0, 'city': 'Unknown'})

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston
4   5   Alice1   35     New York

In [51]:
# 1️⃣3️⃣ isnull() — Check missing values
df.isnull().sum()

id      0
name    0
age     0
city    0
dtype: int64

In [59]:
# 1️⃣4️⃣ value_counts() — Frequency count
df
df['city'].value_counts()

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston
4   5   Alice1   35     New York

city
New York       2
Los Angeles    1
Chicago        1
Houston        1
Name: count, dtype: int64

In [60]:
# 1️⃣5️⃣ to_csv() — Save DataFrame to CSV
df.to_csv('output_0630.csv', index=False)
df

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago
3   4    David   40      Houston
4   5   Alice1   35     New York